IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CLIENTE')
BEGIN
	CREATE TABLE [dbo].[CLIENTE](
		[ID]		[int]		  NOT NULL,
		[NOME]		[varchar](50) NOT NULL,
		[EMAIL]		[varchar](50) NOT NULL,
		[TELEFONE]	[varchar](20) NOT NULL,

		CONSTRAINT PK_CLIENTE PRIMARY KEY (ID)
	) ON [PRIMARY]
END;